name: model-metrics
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: iterative/setup-cml@v1
      - name: Metrics

        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |     
          echo "## Plots" >> report.md
          echo "### correlation Matrix" >> report.md
          cml publish ./images/correlation.png --md >> report.md
          echo "### Feature Importance" >> report.md
          cml publish ./images/feature_importance.png --md >> report.md
          echo "###  Complete causal graph" >> report.md
          cml publish ./images/causal_graph_complete.png --md >> report.md
          echo "###  Complete causal graph with threshold" >> report.md
          cml publish ./images/causal_graph_complete_threshold.png --md >> report.md
          echo "###  causal graph with only directly related features" >> report.md
          cml publish ./images/causal_graph_with_important.png --md >> report.md
          # cat report.md
          cml send-comment report.md